---
- hosts: localhost
  become: true
  vars_files: /tmp/ansible/vars.yml
  tasks:
    - import_tasks: /tmp/ansible/maven.yml
    - import_tasks: /tmp/ansible/jenkins.yml

- hosts: all
  become: true
  vars_files: /tmp/ansible/vars.yml
  tasks:
    - import_tasks: /tmp/ansible/app.yml
...